USE POKEDEX_USIL
GO
INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (1,'Bulbasaur',10,14,45,49,49,65,65,45,'https://img.pokemondb.net/artwork/large/bulbasaur.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (2,'Ivisaur',10,14,60,62,63,80,80,60,'https://img.pokemondb.net/artwork/large/ivysaur.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (3,'Venusaur',10,14,80,82,83,100,100,80,'https://img.pokemondb.net/artwork/large/venusaur.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (4,'Charmander',7,13,39,52,43,60,50,65,'https://img.pokemondb.net/artwork/large/charmander.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (5,'Charmeleon',7,13,58,64,58,80,65,80,'https://img.pokemondb.net/artwork/large/charmeleon.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (6,'Charizard',7,8,78,84,78,109,85,100,'https://img.pokemondb.net/artwork/large/charizard.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (7,'Squirtle',18,13,44,48,65,50,64,43,'https://img.pokemondb.net/artwork/large/squirtle.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (8,'Wartortle',18,13,59,63,80,65,80,58,'https://img.pokemondb.net/artwork/large/wartortle.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (9,'Blastoise',18,13,79,83,100,115,105,78,'https://img.pokemondb.net/artwork/large/blastoise.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (10,'Caterpie',1,13,45,30,35,20,20,45,'https://img.pokemondb.net/artwork/large/caterpie.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (11,'Metapod',1,13,50,20,55,25,25,30,'https://img.pokemondb.net/artwork/large/metapod.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (12,'Butterfree',1,8,60,45,50,90,80,70,'https://img.pokemondb.net/artwork/large/butterfree.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (13,'Weedle',1,14,40,35,30,20,20,50,'https://img.pokemondb.net/artwork/large/weedle.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (14,'Kakuna',1,14,45,25,50,25,25,35,'https://img.pokemondb.net/artwork/large/kakuna.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (15,'Beedrill',1,14,65,90,40,45,80,75,'https://img.pokemondb.net/artwork/large/beedrill.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (16,'Pidgey',13,8,40,45,40,35,35,56,'https://img.pokemondb.net/artwork/large/pidgey.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (17,'Pidgeotto',13,8,63,60,55,50,50,71,'https://img.pokemondb.net/artwork/large/pidgeotto.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (18,'Pidgeot',13,8,83,80,75,70,70,101,'https://img.pokemondb.net/artwork/large/pidgeot.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (19,'Raticate',13,13,55,81,60,50,70,97,'https://img.pokemondb.net/artwork/large/raticate.jpg','ACT');

INSERT INTO POKEMON (POKEMON_ID,NAME,TYPE1_ID,TYPE2_ID,HP,ATTACK,DEFENSE,SPEED_ATTACK,SPEED_DEFENSE,SPEED,IMAGE_DIR,STATE)
VALUES (20,'Spearow',13,8,40,60,60,30,31,100,'https://img.pokemondb.net/artwork/large/spearow.jpg','ACT');

SELECT * FROM POKEMON
