USE POKEDEX_USIL
GO

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (1, 'Insecto','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (2, 'Oscuro','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (3, 'Dragon','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (4, 'Electrico','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (5, 'Hada','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (6, 'Luchador','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (7, 'Fuego','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (8, 'Volador','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (9, 'Fantasma','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (10, 'Planta','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (11, 'Tierra','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (12, 'Hielo','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (13, 'Normal','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (14, 'Veneno','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (15, 'Psiquico','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (16, 'Roca','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (17, 'Metal','ACT');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME,STATE)
VALUES (18, 'Agua','ACT');

GO

SELECT * FROM TYPES
