USE POKEDEX_USIL
GO

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (1, 'Insecto');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (2, 'Oscuro');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (3, 'Dragon');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (4, 'Electrico');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (5, 'Hada');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (6, 'Luchador');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (7, 'Fuego');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (8, 'Volador');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (9, 'Fantasma');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (10, 'Planta');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (11, 'Tierra');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (12, 'Hielo');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (13, 'Normal');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (14, 'Veneno');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (15, 'Psiquico');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (16, 'Roca');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (17, 'Metal');

INSERT INTO TYPES (TYPE_ID, TYPE_NAME)
VALUES (18, 'Agua');

GO

SELECT * FROM TYPES
